Update footer and navbar to match PennyLane website
PennyLaneAI/pennylane-sphinx-theme pull request #29
Opened 2023-09-20 14:53 UTC by Mandrenkov

**Context:**

The PennyLane website is updating the styling of its footer and navbar. For a consistent experience, it makes sense to also update the layout, styling, etc. of the PennyLane Docs pages to match the main website.

**Description of the Change:**

Updated the inherited Xanadu Sphinx Theme (XST) version to v0.4.0 as well as the default navbar and footer options. The technical details of these changes (e.g., CSS modifications) are captured in a [different PR to the XST repository](https://github.com/XanaduAI/xanadu-sphinx-theme/pull/40).

<details><summary>Desktop Navbar</summary>
<p>

<img width="948" alt="Desktop Navbar" src="https://github.com/PennyLaneAI/pennylane-sphinx-theme/assets/5883774/79eafb91-7e03-4470-80f7-f069de5de20e">

</p>
</details> 

<details><summary>Desktop Footer</summary>
<p>

<img width="948" alt="Desktop Footer" src="https://github.com/PennyLaneAI/pennylane-sphinx-theme/assets/5883774/0317edae-1983-4d01-a66b-834c1c614ab5">

</p>
</details> 

<details><summary>Mobile Navbar</summary>
<p>

<img width="417" alt="Mobile Navbar Expanded" src="https://github.com/PennyLaneAI/pennylane-sphinx-theme/assets/5883774/0cf8d084-ccdb-45e1-a8a7-53f481c94e9c">

<img width="420" alt="Mobile Navbar ToC Expanded" src="https://github.com/PennyLaneAI/pennylane-sphinx-theme/assets/5883774/1a3de49f-7f21-4378-baca-bd3fe51235ac">

</p>
</details> 

<details><summary>Mobile Footer</summary>
<p>

<img width="419" alt="Mobile Footer" src="https://github.com/PennyLaneAI/pennylane-sphinx-theme/assets/5883774/c1cfc266-53d6-4901-b5d0-c440ce6d7467">

</p>
</details> 

**Benefits:**

* The navbar and footer on the PennyLane Docs pages will be consistent with the main PennyLane website.

**Possible Drawbacks:**

* Some accessibility features were compromised in the XST v0.4.0 release; however, these will be addressed in a future patch release.

**Related GitHub Issues:**

None.

2023-09-20 15:05 UTC, Mandrenkov commented on .github/CHANGELOG.md
> +  [(#XXX)](https://github.com/PennyLaneAI/pennylane-sphinx-theme/pull/XXX)
```suggestion
  [(#29)](https://github.com/PennyLaneAI/pennylane-sphinx-theme/pull/29)
```

2023-09-20 16:18 UTC, Lorraine-at-Xanadu requested changes
Hey @Mandrenkov! You've done an incredible job matching the navbar in Sphinx. 

1. Learn > Glossary: Link is broken and should go to https://pennylane.ai/qml/glossary
2. When I hover on 'Learn' (for example) and then hover on 'Documentation' there's a delay when the 'Learn' menu closes causing overlap. 

![image](https://github.com/XanaduAI/xanadu-sphinx-theme/assets/112511934/7ccfcbe1-9c0c-4463-b727-01c98a5fc353)

2023-09-20 16:31 UTC, Lorraine-at-Xanadu requested changes
The footer looks good, too, @Mandrenkov. A couple of things...

1. 'FAQ' is missing after 'Glossary' under _For learners_ (https://pennylane.ai/faq).
2. The 'Codebook' link doesn't open to https://codebook.xanadu.ai/ under _For learners_.

2023-09-20 18:05 UTC, Mandrenkov commented
Thanks for the review, @Lorraine-at-Xanadu! I've implemented all the feedback (great catches by the way!).

2023-09-20 19:10 UTC, josh146 approved these changes
😍

2023-09-20 19:57 UTC, Lorraine-at-Xanadu approved these changes
This looks great! Thank you, @Mandrenkov for making the navbar on the Docs pages match the rest of the site.

2023-09-20 20:06 UTC, ashishks0522 reviewed
This is looking great @Mandrenkov!

One different behaviour I noticed is that on [PenyLane NavBar ](https://dev.pennylane.ai/pull_request_previews/605/) we open external links except to docs pages (like to github, discussion fourm etc) in new tab and here we are opening everything in same tab.

I guess this could be more of a product question as well, should we change that here or in the react one?

cc: @Lorraine-at-Xanadu

2023-09-20 21:40 UTC, Lorraine-at-Xanadu commented
> This is looking great @Mandrenkov!
> 
> One different behaviour I noticed is that on [PenyLane NavBar ](https://dev.pennylane.ai/pull_request_previews/605/) we open external links except to docs pages (like to github, discussion fourm etc) in new tab and here we are opening everything in same tab.
> 
> I guess this could be more of a product question as well, should we change that here or in the react one?
> 
> cc: @Lorraine-at-Xanadu

Hi @ashishks0522 and @Mandrenkov! Based on @WillXanadu's design, only the Codebook and Support open in a new tab because those are the only places I see this symbol:
![image](https://github.com/PennyLaneAI/pennylane-sphinx-theme/assets/112511934/48d73823-4b54-436f-99b7-8050517fcdcd)

2023-09-21 00:01 UTC, Mandrenkov commented
Nice catch, @ashishks0522! I've updated the external links to open in a new tab (cc @Lorraine-at-Xanadu).

2023-09-21 13:21 UTC, WillXanadu commented
this looks great @Mandrenkov ! A slight change that was added recently was to change the hover state of the root nav links to blue, instead of the current light grey. Is that something you can easily add in this PR?

2023-09-21 19:23 UTC, ashishks0522 commented
Probably the last change, but as mentioned [here](https://github.com/XanaduAI/pennylane.ai-react/pull/621#pullrequestreview-1638536727) - we would have to remove the `Get Involved` link from the footer 😅

2023-09-21 20:33 UTC, Mandrenkov commented
> Probably the last change, but as mentioned [here](https://github.com/XanaduAI/pennylane.ai-react/pull/621#pullrequestreview-1638536727) - we would have to remove the `Get Involved` link from the footer 😅

Thanks, @ashishks0522! This has been implemented [here](https://github.com/PennyLaneAI/pennylane-sphinx-theme/pull/29/commits/bf6fc292facdc3d5b3989b99f7a849a8f196541a).

2023-09-21 20:45 UTC, ashishks0522 approved these changes

2023-09-21 21:39 UTC, Lorraine-at-Xanadu approved these changes
Hey @Mandrenkov! I double-checked that the changes on the REACT navbar and footer are also working here. This looks great! Thank you.

2023-09-22 15:03 UTC, merged