sc-76288-update-footer-links-to-include-research-page
PennyLaneAI/pennylane-sphinx-theme pull request #68
Opened 2024-11-01 17:48 UTC by ashishks0522

## Changes
- Updated footer links to include `Research` page link
- Updated `Education` label to `Teach

2024-11-01 18:48 UTC, Mandrenkov approved these changes

2024-11-01 18:48 UTC, Mandrenkov commented on .github/CHANGELOG.md
Don't forget to add yourself as a contributor! 👻

2024-11-01 20:31 UTC, Lorraine-at-Xanadu commented
Based on the screenshots, the Sphinx navbar and footer looks good, @ashishks0522. If you can confirm that 'How-to' links to the 'Results' page with `Demos` and the `How-to` category filter already applied, I can approve this PR (see https://github.com/XanaduAI/pennylane.ai-react/pull/1829#issuecomment-2452544110 for reference).

2024-11-01 20:36 UTC, Alan-eMartin approved these changes
Looks good

2024-11-01 20:46 UTC, ashishks0522 commented
> Based on the screenshots, the Sphinx navbar and footer looks good, @ashishks0522. If you can confirm that 'How-to' links to the 'Results' page with `Demos` and the `How-to` category filter already applied, I can approve this PR (see [XanaduAI/pennylane.ai-react#1829 (comment)](https://github.com/XanaduAI/pennylane.ai-react/pull/1829#issuecomment-2452544110) for reference).

Just pushed that change, it should link correctly now 🙂

2024-11-02 01:53 UTC, Mandrenkov commented
Hey @Lorraine-at-Xanadu and @ashishks0522, as an FYI, there are PR preview links for changes to the PST (and XST too)! They're just a little tricky to find. I've attached a screenshot to help. For this PR, the link is [here](https://xanaduai-pennylane--68.com.readthedocs.build/projects/sphinx-theme/en/68/).

![image](https://github.com/user-attachments/assets/a714312d-5659-4c20-9852-1bd086e88ed4)

2024-11-04 14:25 UTC, Lorraine-at-Xanadu requested changes
Hi @ashishks0522! There are a couple of links that don't work, but I'm not sure if it's just in the PR preview.

1. Clicking on `Why PennyLane` should link to the new 'Research' page.
2. Clicking on `Ecosystem` should link to the 'Get involved' page. Currently, it links to a 404 Read the Docs page (see screenshot).

<img width="958" alt="image" src="https://github.com/user-attachments/assets/6960b4de-07f2-4951-a6f4-eeb986ac32ad">

2024-11-04 14:43 UTC, ashishks0522 commented on pennylane_sphinx_theme/navbar.py
> +        "href": "/get-involved",
Thanks @Mandrenkov, copy paste from `pennylane.ai-react` got me there 😬

2024-11-04 14:47 UTC, ashishks0522 commented
> Clicking on Why PennyLane should link to the new 'Research' page.

@Lorraine-at-Xanadu this will work once the research page is live, right now Research page changes are in a PR to be merged in. I have tagged you in the final [PR](https://github.com/XanaduAI/pennylane.ai-react/pull/1824) for QA and mentioned these caveats in the description.

Other links should work as expected now, thanks @Mandrenkov for the suggestions.

2024-11-04 15:37 UTC, Mandrenkov approved these changes

2024-11-06 21:48 UTC, Lorraine-at-Xanadu approved these changes
This looks great, @ashishks0522. Thank you very much.

2024-11-06 21:58 UTC, merged